export const LEGACY_KNOWLEDGE_PUBLISHER = Symbol("LEGACY_KNOWLEDGE_PUBLISHER");
export const KNOWLEDGE_V2_RUNTIME_RETRIEVER = Symbol("KNOWLEDGE_V2_RUNTIME_RETRIEVER");
export const KNOWLEDGE_V2_GROUNDED_ANSWER = Symbol("KNOWLEDGE_V2_GROUNDED_ANSWER");
export const KNOWLEDGE_V2_QUERY_HASH_KEYRING = Symbol("KNOWLEDGE_V2_QUERY_HASH_KEYRING");
